/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server;

//@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
//@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-05-02")
public class Writeoff implements org.apache.thrift.TBase<Writeoff, Writeoff._Fields>, java.io.Serializable, Cloneable, Comparable<Writeoff> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Writeoff");

  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CODE_CABINET_FIELD_DESC = new org.apache.thrift.protocol.TField("codeCabinet", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField CODE_EQUIPMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("codeEquipment", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("number", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("date", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CAUSE_FIELD_DESC = new org.apache.thrift.protocol.TField("cause", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new WriteoffStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new WriteoffTupleSchemeFactory();

  public int code; // required
  public int codeCabinet; // required
  public int codeEquipment; // required
  public int number; // required
  public java.lang.String date; // required
  public java.lang.String cause; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CODE((short)1, "code"),
    CODE_CABINET((short)2, "codeCabinet"),
    CODE_EQUIPMENT((short)3, "codeEquipment"),
    NUMBER((short)4, "number"),
    DATE((short)5, "date"),
    CAUSE((short)6, "cause");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODE
          return CODE;
        case 2: // CODE_CABINET
          return CODE_CABINET;
        case 3: // CODE_EQUIPMENT
          return CODE_EQUIPMENT;
        case 4: // NUMBER
          return NUMBER;
        case 5: // DATE
          return DATE;
        case 6: // CAUSE
          return CAUSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CODE_ISSET_ID = 0;
  private static final int __CODECABINET_ISSET_ID = 1;
  private static final int __CODEEQUIPMENT_ISSET_ID = 2;
  private static final int __NUMBER_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.CODE_CABINET, new org.apache.thrift.meta_data.FieldMetaData("codeCabinet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.CODE_EQUIPMENT, new org.apache.thrift.meta_data.FieldMetaData("codeEquipment", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.NUMBER, new org.apache.thrift.meta_data.FieldMetaData("number", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.DATE, new org.apache.thrift.meta_data.FieldMetaData("date", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CAUSE, new org.apache.thrift.meta_data.FieldMetaData("cause", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Writeoff.class, metaDataMap);
  }

  public Writeoff() {
  }

  public Writeoff(
    int code,
    int codeCabinet,
    int codeEquipment,
    int number,
    java.lang.String date,
    java.lang.String cause)
  {
    this();
    this.code = code;
    setCodeIsSet(true);
    this.codeCabinet = codeCabinet;
    setCodeCabinetIsSet(true);
    this.codeEquipment = codeEquipment;
    setCodeEquipmentIsSet(true);
    this.number = number;
    setNumberIsSet(true);
    this.date = date;
    this.cause = cause;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Writeoff(Writeoff other) {
    __isset_bitfield = other.__isset_bitfield;
    this.code = other.code;
    this.codeCabinet = other.codeCabinet;
    this.codeEquipment = other.codeEquipment;
    this.number = other.number;
    if (other.isSetDate()) {
      this.date = other.date;
    }
    if (other.isSetCause()) {
      this.cause = other.cause;
    }
  }

  public Writeoff deepCopy() {
    return new Writeoff(this);
  }

  @Override
  public void clear() {
    setCodeIsSet(false);
    this.code = 0;
    setCodeCabinetIsSet(false);
    this.codeCabinet = 0;
    setCodeEquipmentIsSet(false);
    this.codeEquipment = 0;
    setNumberIsSet(false);
    this.number = 0;
    this.date = null;
    this.cause = null;
  }

  public int getCode() {
    return this.code;
  }

  public Writeoff setCode(int code) {
    this.code = code;
    setCodeIsSet(true);
    return this;
  }

  public void unsetCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CODE_ISSET_ID);
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CODE_ISSET_ID);
  }

  public void setCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CODE_ISSET_ID, value);
  }

  public int getCodeCabinet() {
    return this.codeCabinet;
  }

  public Writeoff setCodeCabinet(int codeCabinet) {
    this.codeCabinet = codeCabinet;
    setCodeCabinetIsSet(true);
    return this;
  }

  public void unsetCodeCabinet() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CODECABINET_ISSET_ID);
  }

  /** Returns true if field codeCabinet is set (has been assigned a value) and false otherwise */
  public boolean isSetCodeCabinet() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CODECABINET_ISSET_ID);
  }

  public void setCodeCabinetIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CODECABINET_ISSET_ID, value);
  }

  public int getCodeEquipment() {
    return this.codeEquipment;
  }

  public Writeoff setCodeEquipment(int codeEquipment) {
    this.codeEquipment = codeEquipment;
    setCodeEquipmentIsSet(true);
    return this;
  }

  public void unsetCodeEquipment() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CODEEQUIPMENT_ISSET_ID);
  }

  /** Returns true if field codeEquipment is set (has been assigned a value) and false otherwise */
  public boolean isSetCodeEquipment() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CODEEQUIPMENT_ISSET_ID);
  }

  public void setCodeEquipmentIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CODEEQUIPMENT_ISSET_ID, value);
  }

  public int getNumber() {
    return this.number;
  }

  public Writeoff setNumber(int number) {
    this.number = number;
    setNumberIsSet(true);
    return this;
  }

  public void unsetNumber() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMBER_ISSET_ID);
  }

  /** Returns true if field number is set (has been assigned a value) and false otherwise */
  public boolean isSetNumber() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMBER_ISSET_ID);
  }

  public void setNumberIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMBER_ISSET_ID, value);
  }

  public java.lang.String getDate() {
    return this.date;
  }

  public Writeoff setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  public void unsetDate() {
    this.date = null;
  }

  /** Returns true if field date is set (has been assigned a value) and false otherwise */
  public boolean isSetDate() {
    return this.date != null;
  }

  public void setDateIsSet(boolean value) {
    if (!value) {
      this.date = null;
    }
  }

  public java.lang.String getCause() {
    return this.cause;
  }

  public Writeoff setCause(java.lang.String cause) {
    this.cause = cause;
    return this;
  }

  public void unsetCause() {
    this.cause = null;
  }

  /** Returns true if field cause is set (has been assigned a value) and false otherwise */
  public boolean isSetCause() {
    return this.cause != null;
  }

  public void setCauseIsSet(boolean value) {
    if (!value) {
      this.cause = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((java.lang.Integer)value);
      }
      break;

    case CODE_CABINET:
      if (value == null) {
        unsetCodeCabinet();
      } else {
        setCodeCabinet((java.lang.Integer)value);
      }
      break;

    case CODE_EQUIPMENT:
      if (value == null) {
        unsetCodeEquipment();
      } else {
        setCodeEquipment((java.lang.Integer)value);
      }
      break;

    case NUMBER:
      if (value == null) {
        unsetNumber();
      } else {
        setNumber((java.lang.Integer)value);
      }
      break;

    case DATE:
      if (value == null) {
        unsetDate();
      } else {
        setDate((java.lang.String)value);
      }
      break;

    case CAUSE:
      if (value == null) {
        unsetCause();
      } else {
        setCause((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CODE:
      return getCode();

    case CODE_CABINET:
      return getCodeCabinet();

    case CODE_EQUIPMENT:
      return getCodeEquipment();

    case NUMBER:
      return getNumber();

    case DATE:
      return getDate();

    case CAUSE:
      return getCause();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CODE:
      return isSetCode();
    case CODE_CABINET:
      return isSetCodeCabinet();
    case CODE_EQUIPMENT:
      return isSetCodeEquipment();
    case NUMBER:
      return isSetNumber();
    case DATE:
      return isSetDate();
    case CAUSE:
      return isSetCause();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Writeoff)
      return this.equals((Writeoff)that);
    return false;
  }

  public boolean equals(Writeoff that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_code = true;
    boolean that_present_code = true;
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (this.code != that.code)
        return false;
    }

    boolean this_present_codeCabinet = true;
    boolean that_present_codeCabinet = true;
    if (this_present_codeCabinet || that_present_codeCabinet) {
      if (!(this_present_codeCabinet && that_present_codeCabinet))
        return false;
      if (this.codeCabinet != that.codeCabinet)
        return false;
    }

    boolean this_present_codeEquipment = true;
    boolean that_present_codeEquipment = true;
    if (this_present_codeEquipment || that_present_codeEquipment) {
      if (!(this_present_codeEquipment && that_present_codeEquipment))
        return false;
      if (this.codeEquipment != that.codeEquipment)
        return false;
    }

    boolean this_present_number = true;
    boolean that_present_number = true;
    if (this_present_number || that_present_number) {
      if (!(this_present_number && that_present_number))
        return false;
      if (this.number != that.number)
        return false;
    }

    boolean this_present_date = true && this.isSetDate();
    boolean that_present_date = true && that.isSetDate();
    if (this_present_date || that_present_date) {
      if (!(this_present_date && that_present_date))
        return false;
      if (!this.date.equals(that.date))
        return false;
    }

    boolean this_present_cause = true && this.isSetCause();
    boolean that_present_cause = true && that.isSetCause();
    if (this_present_cause || that_present_cause) {
      if (!(this_present_cause && that_present_cause))
        return false;
      if (!this.cause.equals(that.cause))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + code;

    hashCode = hashCode * 8191 + codeCabinet;

    hashCode = hashCode * 8191 + codeEquipment;

    hashCode = hashCode * 8191 + number;

    hashCode = hashCode * 8191 + ((isSetDate()) ? 131071 : 524287);
    if (isSetDate())
      hashCode = hashCode * 8191 + date.hashCode();

    hashCode = hashCode * 8191 + ((isSetCause()) ? 131071 : 524287);
    if (isSetCause())
      hashCode = hashCode * 8191 + cause.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Writeoff other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCodeCabinet()).compareTo(other.isSetCodeCabinet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCodeCabinet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.codeCabinet, other.codeCabinet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCodeEquipment()).compareTo(other.isSetCodeEquipment());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCodeEquipment()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.codeEquipment, other.codeEquipment);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNumber()).compareTo(other.isSetNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.number, other.number);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDate()).compareTo(other.isSetDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.date, other.date);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCause()).compareTo(other.isSetCause());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCause()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cause, other.cause);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Writeoff(");
    boolean first = true;

    sb.append("code:");
    sb.append(this.code);
    first = false;
    if (!first) sb.append(", ");
    sb.append("codeCabinet:");
    sb.append(this.codeCabinet);
    first = false;
    if (!first) sb.append(", ");
    sb.append("codeEquipment:");
    sb.append(this.codeEquipment);
    first = false;
    if (!first) sb.append(", ");
    sb.append("number:");
    sb.append(this.number);
    first = false;
    if (!first) sb.append(", ");
    sb.append("date:");
    if (this.date == null) {
      sb.append("null");
    } else {
      sb.append(this.date);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cause:");
    if (this.cause == null) {
      sb.append("null");
    } else {
      sb.append(this.cause);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WriteoffStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public WriteoffStandardScheme getScheme() {
      return new WriteoffStandardScheme();
    }
  }

  private static class WriteoffStandardScheme extends org.apache.thrift.scheme.StandardScheme<Writeoff> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Writeoff struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.code = iprot.readI32();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CODE_CABINET
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.codeCabinet = iprot.readI32();
              struct.setCodeCabinetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CODE_EQUIPMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.codeEquipment = iprot.readI32();
              struct.setCodeEquipmentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.number = iprot.readI32();
              struct.setNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.date = iprot.readString();
              struct.setDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CAUSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cause = iprot.readString();
              struct.setCauseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Writeoff struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CODE_FIELD_DESC);
      oprot.writeI32(struct.code);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CODE_CABINET_FIELD_DESC);
      oprot.writeI32(struct.codeCabinet);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CODE_EQUIPMENT_FIELD_DESC);
      oprot.writeI32(struct.codeEquipment);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUMBER_FIELD_DESC);
      oprot.writeI32(struct.number);
      oprot.writeFieldEnd();
      if (struct.date != null) {
        oprot.writeFieldBegin(DATE_FIELD_DESC);
        oprot.writeString(struct.date);
        oprot.writeFieldEnd();
      }
      if (struct.cause != null) {
        oprot.writeFieldBegin(CAUSE_FIELD_DESC);
        oprot.writeString(struct.cause);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WriteoffTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public WriteoffTupleScheme getScheme() {
      return new WriteoffTupleScheme();
    }
  }

  private static class WriteoffTupleScheme extends org.apache.thrift.scheme.TupleScheme<Writeoff> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Writeoff struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCode()) {
        optionals.set(0);
      }
      if (struct.isSetCodeCabinet()) {
        optionals.set(1);
      }
      if (struct.isSetCodeEquipment()) {
        optionals.set(2);
      }
      if (struct.isSetNumber()) {
        optionals.set(3);
      }
      if (struct.isSetDate()) {
        optionals.set(4);
      }
      if (struct.isSetCause()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetCode()) {
        oprot.writeI32(struct.code);
      }
      if (struct.isSetCodeCabinet()) {
        oprot.writeI32(struct.codeCabinet);
      }
      if (struct.isSetCodeEquipment()) {
        oprot.writeI32(struct.codeEquipment);
      }
      if (struct.isSetNumber()) {
        oprot.writeI32(struct.number);
      }
      if (struct.isSetDate()) {
        oprot.writeString(struct.date);
      }
      if (struct.isSetCause()) {
        oprot.writeString(struct.cause);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Writeoff struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.code = iprot.readI32();
        struct.setCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.codeCabinet = iprot.readI32();
        struct.setCodeCabinetIsSet(true);
      }
      if (incoming.get(2)) {
        struct.codeEquipment = iprot.readI32();
        struct.setCodeEquipmentIsSet(true);
      }
      if (incoming.get(3)) {
        struct.number = iprot.readI32();
        struct.setNumberIsSet(true);
      }
      if (incoming.get(4)) {
        struct.date = iprot.readString();
        struct.setDateIsSet(true);
      }
      if (incoming.get(5)) {
        struct.cause = iprot.readString();
        struct.setCauseIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

